version: '3.8'
services:

  mongo-db:
    image: mongo:4.4.25-focal
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=user
    #      - MONGO_INITDB_ROOT_PASSWORD=password
    #      - MONGO_INITDB_DATABASE=advices
    ports:
      - "27017:27017"

  mongoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongo-db:27017
    #      - spring.data.mongodb.uri=mongodb://host.docker.internal:27017/advices
    depends_on:
      - mongo-db